spring.application.name=OWP
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
