CREATE TABLE booking
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT      NOT NULL,
    movie_id     INT      NOT NULL,
    booking_date TIMESTAMP   NOT NULL,
    status       VARCHAR(30) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (movie_id) REFERENCES movie(id)
);